---
openapi: 3.0.3
tags:
  - name: Launchpad Group REST API
  - name: Launchpad REST API
  - name: Launchpad Tile REST API
paths:
  /launchpad:
    get:
      tags:
        - Launchpad REST API
      description: Get all launchpads and handle filters
      operationId: getAllLaunchpadsFiltered
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: portalId
          in: query
          schema:
            type: string
        - name: type
          in: query
          schema:
            $ref: '#/components/schemas/LaunchpadType'
        - name: userGroupId
          in: query
          schema:
            type: string
        - name: userId
          in: query
          schema:
            type: string
        - name: userOrganizationId
          in: query
          schema:
            type: string
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LaunchpadDTO'
    post:
      tags:
        - Launchpad REST API
      description: Add a new launchpad to the portal
      operationId: addNewLaunchpad
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchpadCreateDTO'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchpadDTO'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
  /launchpad-group/{id}:
    get:
      tags:
        - Launchpad Group REST API
      description: Get launchpad group by id
      operationId: getLaunchpadGroupById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchpadGroupDTO'
    put:
      tags:
        - Launchpad Group REST API
      description: Update an existing launchpad group
      operationId: updateLaunchpadGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchpadGroupUpdateDTO'
      responses:
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchpadGroupDTO'
    delete:
      tags:
        - Launchpad Group REST API
      description: Remove launchpad group
      operationId: removeLaunchpadGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchpadDTO'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
  /launchpad-group/{id}/tiles:
    post:
      tags:
        - Launchpad Group REST API
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchpadTileDTO'
      responses:
        "200":
          description: OK
  /launchpad-tile/{id}:
    put:
      tags:
        - Launchpad Tile REST API
      description: Update an existing launchpad tile
      operationId: updateLaunchpadTile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchpadTileUpdateDTO'
      responses:
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchpadTileDTO'
  /launchpad/shared:
    get:
      tags:
        - Launchpad REST API
      description: Get shared launchpads in current portal
      operationId: getSharedLaunchpadsInPortal
      parameters:
        - name: portalId
          in: query
          required: true
          schema:
            type: string
            nullable: false
        - name: userId
          in: query
          required: true
          schema:
            type: string
            nullable: false
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LaunchpadDTO'
  /launchpad/{id}:
    delete:
      tags:
        - Launchpad REST API
      description: Delete launchpad by id
      operationId: deleteLaunchpadById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "204":
          description: No content
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
  /launchpad/{id}/groups:
    post:
      tags:
        - Launchpad REST API
      description: Create and insert new launchpad group to launchpad with given id
      operationId: insertNewLaunchpadGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchpadGroupCreateDTO'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchpadGroupDTO'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
  /launchpad/{id}/tiles:
    post:
      tags:
        - Launchpad REST API
      description: Insert tile to default group of launchpad with given id
      operationId: insertTileToDefaultGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LaunchpadTileCreateDTO'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LaunchpadDTO'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    LaunchpadType:
      enum:
        - PRIVATE
        - SHARED
      type: string
    LaunchpadCreateDTO:
      required:
        - type
      type: object
      properties:
        description:
          type: string
        name:
          pattern: \S
          type: string
          nullable: false
        portalId:
          pattern: \S
          type: string
          nullable: false
        type:
          allOf:
            - $ref: '#/components/schemas/LaunchpadType'
            - enum:
                - PRIVATE
                - SHARED
              nullable: false
        userGroupId:
          type: string
        userId:
          type: string
        userOrganizationId:
          type: string
    LaunchpadGroupDTO:
      type: object
      properties:
        defaultGroup:
          type: boolean
        description:
          type: string
        launchpadId:
          format: int64
          type: integer
        name:
          pattern: \S
          type: string
          nullable: false
        sortOrder:
          format: int64
          type: integer
        tiles:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/LaunchpadTileDTO'
    LaunchpadTileDTO:
      required:
        - type
      type: object
      properties:
        appId:
          pattern: \S
          type: string
          nullable: false
        appUrl:
          pattern: \S
          type: string
          nullable: false
        description:
          type: string
        icon:
          type: string
        launchpadGroupId:
          type: string
        name:
          pattern: \S
          type: string
          nullable: false
        sortOrder:
          format: int64
          type: integer
        type:
          allOf:
            - $ref: '#/components/schemas/TileType'
            - enum:
                - APPLICATION
                - FAVOURITE
              nullable: false
    TileType:
      enum:
        - APPLICATION
        - FAVOURITE
      type: string
    LaunchpadDTO:
      required:
        - type
      type: object
      properties:
        description:
          type: string
        groups:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/LaunchpadGroupDTO'
        name:
          pattern: \S
          type: string
          nullable: false
        portalId:
          pattern: \S
          type: string
          nullable: false
        type:
          allOf:
            - $ref: '#/components/schemas/LaunchpadType'
            - enum:
                - PRIVATE
                - SHARED
              nullable: false
        userGroupId:
          type: string
        userId:
          type: string
        userOrganizationId:
          type: string
    LaunchpadGroupCreateDTO:
      type: object
      properties:
        description:
          type: string
        name:
          pattern: \S
          type: string
          nullable: false
    LaunchpadTileCreateDTO:
      required:
        - type
      type: object
      properties:
        appId:
          pattern: \S
          type: string
          nullable: false
        appUrl:
          pattern: \S
          type: string
          nullable: false
        description:
          type: string
        icon:
          type: string
        name:
          pattern: \S
          type: string
          nullable: false
        type:
          allOf:
            - $ref: '#/components/schemas/TileType'
            - enum:
                - APPLICATION
                - FAVOURITE
              nullable: false
    LaunchpadGroupUpdateDTO:
      required:
        - launchpadId
      type: object
      properties:
        description:
          type: string
        launchpadId:
          format: int64
          type: integer
          nullable: false
        name:
          pattern: \S
          type: string
          nullable: false
    LaunchpadTileUpdateDTO:
      type: object
      properties:
        launchpadGroupId:
          pattern: \S
          type: string
          nullable: false
        name:
          pattern: \S
          type: string
          nullable: false
